shellEmulator: true
trustPolicy: no-downgrade

packages:
  - 'packages/*'

catalog:
  '@antfu/eslint-config': ^9.3.0
  '@arethetypeswrong/cli': ^0.18.5
  '@types/node': ^26.2.0
  bumpp: ^12.2.0
  eslint: ^10.8.1
  eslint-plugin-harlanzw: ^0.17.1
  lint-staged: ^17.3.0
  obuild: ^0.4.38
  typescript: 6.0.3
  vitest: ^4.1.10

ignoredBuiltDependencies:
  - esbuild
trustPolicyIgnoreAfter: 262800
