// Generated by ts-to-zod
import { z } from "zod";

export const linkSchema = z.object({
    as: z.union([z.literal("audio"), z.literal("document"), z.literal("embed"), z.literal("fetch"), z.literal("font"), z.literal("image"), z.literal("object"), z.literal("script"), z.literal("style"), z.literal("track"), z.literal("video"), z.literal("worker")]),
    crossorigin: z.union([z.literal(""), z.literal("anonymous"), z.literal("use-credentials")]),
    fetchpriority: z.union([z.literal("high"), z.literal("low"), z.literal("auto")]),
    href: z.string(),
    hreflang: z.string(),
    imagesizes: z.string(),
    imagesrcset: z.string(),
    integrity: z.string(),
    media: z.string(),
    prefetch: z.string(),
    referrerpolicy: z.union([z.literal(""), z.literal("no-referrer"), z.literal("no-referrer-when-downgrade"), z.literal("origin"), z.literal("origin-when-cross-origin"), z.literal("same-origin"), z.literal("strict-origin"), z.literal("strict-origin-when-cross-origin"), z.literal("unsafe-url")]),
    rel: z.union([z.literal("alternate"), z.literal("author"), z.literal("shortcut icon"), z.literal("bookmark"), z.literal("canonical"), z.literal("dns-prefetch"), z.literal("external"), z.literal("help"), z.literal("icon"), z.literal("license"), z.literal("manifest"), z.literal("me"), z.literal("modulepreload"), z.literal("next"), z.literal("nofollow"), z.literal("noopener"), z.literal("noreferrer"), z.literal("opener"), z.literal("pingback"), z.literal("preconnect"), z.literal("prefetch"), z.literal("preload"), z.literal("prerender"), z.literal("prev"), z.literal("search"), z.literal("shortlink"), z.literal("stylesheet"), z.literal("tag"), z.literal("apple-touch-icon"), z.literal("apple-touch-startup-image")]),
    sizes: z.string(),
    title: z.string(),
    type: z.string(),
    key: z.string()
});

export const linkEntriesSchema = z.array(linkSchema.partial());
